spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: su
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
jwt:
  secret-key: ${JWT_SECRET_KEY:secret}